### ISSUE TITLE
m2r is incompatible with Sphinx 3.x.x and above

### ISSUE THREAD

**Issue by AndyEngland521** [sparkfun/Qwiic_Template_Py#1]
See issue https://github.com/sphinx-doc/sphinx/issues/7420

I was unable to get the `m2r2` fix described in this issue to work. A little more digging needs to be done, but know that you can still generate documentation by rolling back to Sphinx 2.4.4

**Comment by santaimpersonator** [comment]
@AndyEngland521 Fixed in this commit: https://github.com/sparkfun/Qwiic_Template_Py/commit/b79d2ac96e38f0e45e615231302e25fe0d9eb4a6

The module just needs to be updated from `m2r` to `m2r2` in the following locations:
- https://github.com/sparkfun/Qwiic_Template_Py/blob/master/docs/conf.py#L37
- https://github.com/sparkfun/Qwiic_Template_Py/blob/master/docs/requirements.txt#L1

_(*I think we were just missing the the change in the `requirements.txt` file. Pushing those changes in your repo, should allow the ReadtheDocs page to build automatically... it may take a minute or two to build.)_
